#ddev-generated
services:
  cypress:
    container_name: ddev-${DDEV_SITENAME}-cypress
    hostname: ${DDEV_SITENAME}-cypress
    image: cypress/included:15.10.0
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    working_dir: /e2e
    user: "${UID:-1000}:${GID:-1000}"
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - CYPRESS_baseUrl=${DDEV_PRIMARY_URL}
      - ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu --disable-software-rasterizer
    volumes:
      - ..:/e2e:cached
      - ".:/mnt/ddev_config"
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: []
    command: ["tail", "-f", "/dev/null"]